### ISSUE TITLE
Custom {chainName} support

### ISSUE THREAD

**Issue by Jonybang** [cybercongress/cyber-search#102]
Is it possible to support custom {chainName} by pass some parameters or configuration with network ports and the chain on which the network is based?

**Comment by hleb-albau** [comment]
Hi @Jonybang,
Do you mean add new chain(not ethereum based, or bitcoin based)? If so, then you need to write "pump" module(like for ethereum). Each chain has unique entities with unique fields, so there is no common chain integrator.  Watch  #92 issue progress for new chains integration guide.

**Comment by Jonybang** [comment]
For a start, I'd like to try to add my chain as ethereum based. In this case, do I need to write my own pump?

**Comment by hleb-albau** [comment]
@Jonybang Yeah, nice catch, Right now it is possible to index only ethereum and ethereum classic chains. But, you can also index you chain under Ethereum name. So all api will be under **/ethereum/xxxx**. I think we should not use [this enum](https://github.com/cybercongress/cyber-search/blob/master/common/src/main/kotlin/fund/cyber/search/model/chains/Ethereum.kt) and just take name from parameter.
We will do it next sprint, stay tuned and index under Ethereum name right now.

**Comment by hleb-albau** [comment]
Should also provide same logic for cassandra service, search api, dump and contract summary.

**Comment by hleb-albau** [comment]
Also https://projectreactor.io/docs/kafka/release/reference/
