### ISSUE TITLE
Create API for search results preview

### ISSUE THREAD

**Issue by asadovka** [cybercongress/cyber-search#108]
Create API for entities preview according to search page requirements:

https://github.com/cybercongress/cyber-browser/blob/master/browser-design/Search_Results_Page.png

- Block
- Uncle
- Contract
- Transaction

**Comment by asadovka** [comment]
https://github.com/cybercongress/cyber-browser/wiki/Vision-&-Scope

search results page

**Comment by 21xhipster** [comment]
@asadovka 
```
There are 4 types of objects that can be foung in listed systems:
1. Contracts
2. Transactions
3. Blocks
4. Uncle blocks
```

What about chaingear objects?
