### ISSUE TITLE
Make search API logic dependent of existing keyspaces

### ISSUE THREAD

**Issue by arturalbov** [cybercongress/cyber-search#113]
How it works now: independent of what keyspaces Cassandra has, Search API tries to create routes for all chain families that we have in support. If there is no keyspace in Cassandra for specific chain Search API fails to start.

How it should work: On start Search API should dynamically find existing keyspaces in Cassandra (keyspaces equals to already indexed chains) by chain family pattern and create routes based on those keyspaces. 
For example, if we have ethereum, ethereum_classic keyspaces it should create routes only for those 2 chains.

**Comment by hleb-albau** [comment]
Tested on my local machine, all is ok.
