### ISSUE TITLE
Add Ethereum Pump/Dump Search Demo Quick Run

### ISSUE THREAD

**Issue by hleb-albau** [cybercongress/cyber-search#116]
I want to add demo of quick running ethereum pump/dump search.

- [x] write docker-compose file
- [x] add dashboards
- [ ] add guide
- [ ] update readme

**Comment by litvintech** [comment]
@hleb-albau what is this issue about?)

**Comment by 21xhipster** [comment]
@litvintech about adding Ethereum based chains to cyber-search e.g. PoA networks
