### ISSUE TITLE
Bring all hashes to one format

### ISSUE THREAD

**Issue by arturalbov** [cybercongress/cyber-search#121]
Now for ethereum we store hashes in 0x... format. For example 0x0a71e02862fd7618500de1915bf1274a97a75b8e0866b3b9d15d0c5e34bc7166

For bitcoin we have another format (without 0x). For example  0a71e02862fd7618500de1915bf1274a97a75b8e0866b3b9d15d0c5e34bc7166

All hashes should be in one format without 0x.

**Comment by 21xhipster** [comment]
Why?

**Comment by hleb-albau** [comment]
@21xhipster What why? Please, be more specific.

**Comment by 21xhipster** [comment]
@hleb-albau After discussion no questions
