### ISSUE TITLE
Slow work of cybersearch.live

### ISSUE THREAD

**Issue by 21xhipster** [cybercongress/cyber-search#133]
Sometime it loads several minutes. Sometime never.
It seems that the thing is really useful, thus a problem

**Comment by cyberadmin** [comment]
Depends on https://github.com/cybercongress/cyber-search/issues/144

**Comment by arturalbov** [comment]
Issue moved to [cybercongress/cybernode #62](https://github.com/cybercongress/cybernode/issues/62) via [**ZenHub**](https://www.zenhub.com/)
