### ISSUE TITLE
Test BTC contracts balances

### ISSUE THREAD

**Issue by arturalbov** [cybercongress/cyber-search#167]
Test BTC contract summary API.
Check that balances calculated right.

**Comment by arturalbov** [comment]
Wrong balance http://api.cybersearch.io/bitcoin/contract/17A16QmavnUfCW11DAApiJxp7ARnxN5pGX

**Comment by hleb-albau** [comment]
We have balance same as here:
https://blockexplorer.com/address/17A16QmavnUfCW11DAApiJxp7ARnxN5pGX

**Comment by hleb-albau** [comment]
Also, all tree exploreres have different balance and total output values:
https://blockexplorer.com/address/17A16QmavnUfCW11DAApiJxp7ARnxN5pGX
https://blockchair.com/bitcoin/address/17A16QmavnUfCW11DAApiJxp7ARnxN5pGX
https://blockchain.info/address/17A16QmavnUfCW11DAApiJxp7ARnxN5pGX

**Comment by hleb-albau** [comment]
So, blockchair.com and blockchain.info also include mempool balances into final one. After all mempool transactions were confirmed, all balances comes into single value. Closed. All wrong balances, right now should be handle separately.
