### ISSUE TITLE
Setup Ethereum mempool indexation

### ISSUE THREAD

**Issue by litvintech** [cybercongress/cyber-search#22]

**Comment by litvintech** [comment]
@YodaMike We already tested Ethereum online processing and chain reorganization with mempool
Is there needed new issues to fix problems which we found (and add dependency) or we can close this task?

**Comment by YodaMike** [comment]
Depends on #46

**Comment by hleb-albau** [comment]
@arturalbov Also, consider to save transaction propagation time(when tx reach mempool) in separate  field in tx.
