### ISSUE TITLE
Provide statistics for cyber search landing

### ISSUE THREAD

**Issue by arturalbov** [cybercongress/cyber-search#239]
- [ ] Discuss what statistics and charts should be shown on cyber search landing page @xhipster @litvintech @hleb-albau @asadovka @SaveTheAles 
- [ ] Implement agreed charts and stats

**Comment by SaveTheAles** [comment]
@arturalbov @hleb-albau @xhipster @litvintech @asadovka  as you think what stats we should to show at landing-page?

**Comment by SaveTheAles** [comment]
@litvintech 
Am I right, you want to provide this landing just for developers?
Thank you for your opinion and bear in mind that we have just one section for this stats. 

p.s. I think we don't need to overload current page. So let show just necessary stats.

**Comment by SaveTheAles** [comment]
@hleb-albau @arturalbov 
Any ideas?

**Comment by arturalbov** [comment]
I'm agree that we should show API stats (total number of txes, blockchains and total index size)
Also may be show single chart with transactions count per minute/10minutess/hour in each blockhain

**Comment by SaveTheAles** [comment]
@arturalbov @litvintech @xhipster @hleb-albau @asadovka 

In this case let's stop on this for first time
