### ISSUE TITLE
API: Expose index stats

### ISSUE THREAD

**Issue by abitrolly** [cybercongress/cyber-search#30]
We need to see through `cyber-ui` when indexator is not functional. For example, when it can not access underlying Parity server.

Possible implementation is that the error should propagate to http://search.cyber.fund/cybernode status page and change the `cyber-search` status to yellow with exact message "ETH node (Parity) is not accessible for indexing".

**Comment by hleb-albau** [comment]
Is this functionality really needed? We will have page with latest blocks for all systems, we will have page with index size, count and etc cluster info.

**Comment by abitrolly** [comment]
Yes. This is really needed.

The story is that person wants to find his transaction that was just posted on the chain. He opens search, enters transaction and gets nothing. Status shows green. The person leaves.

If indexator does not function, and error message is exposed in http://search.cyber.fund/cybernode UI together with yellow status. This creates a feedback loop with a user and tells him what's going on. User can report specific error to us and track the progress. Makes it cybernetic. )

**Comment by abitrolly** [comment]
> We will have page with latest blocks for all systems, we will have page with index size, count and etc cluster info.

How do you see API that returns cluster info page? The critical part is only the service health check with error message in UI, so maybe leave cluster info and status checks separated.

**Comment by litvintech** [comment]
@YodaMike please comment on API for state of indexation story
* API with stats from Elastic (from Elassandra)
* API for indexation status (how many blocks indexed and how many are left)

**Comment by YodaMike** [comment]
1. API for indices stats is implemented, there are pretty big json with a lot of stats so it is necessary to identify which data is needed.
2. we need to implement API for information about not indexed data (remained blocks)

**Comment by hleb-albau** [comment]
@SiarheiSadau we should discuss, where and what info we will show to the users and then define goals for this task

**Comment by abitrolly** [comment]
Feel free to discuss it right here. What is wrong with the scheme suggested
in initial issue comment?

**Comment by hleb-albau** [comment]
@abitrolly It's not wrong, we should just explicit declare what to expose according to cyber-browser requirements. I just want more info here.

**Comment by hleb-albau** [comment]
http://browser.cybersearch.io/

https://github.com/cybercongress/cyber-browser/blob/master/docs/Software_Requirements.md#1-main-page

Search in [134 M] transactions in [2] blockchain systems with [135] parsed tokens. Database size : [369 GBs]

**Comment by arturalbov** [comment]
Endpoint for statistics: http://api.cybersearch.io/search/stats
