### ISSUE TITLE
Bitcoin pump doesn't download blocks after 200k blocks

### ISSUE THREAD

**Issue by hleb-albau** [cybercongress/cyber-search#34]
```
12:49:29.301 [main] INFO fund.cyber.pump.ChainPump - BITCOIN pump start block number is 227602
12:49:33.915 [main] INFO fund.cyber.pump.ChainPump - BITCOIN pump is started
12:49:33.921 [RxCachedThreadScheduler-2] DEBUG f.c.pump.ConcurrentPulledBlockchain - Looking for 227602-227606 blocks for BITCOIN
12:50:43.987 [RxCachedThreadScheduler-6] DEBUG f.c.p.b.JsonRpcBlockToBitcoinBundleConverter - Transactions - Total ids: 224, Cache hits: 35
12:51:32.624 [RxCachedThreadScheduler-7] DEBUG f.c.p.b.JsonRpcBlockToBitcoinBundleConverter - Transactions - Total ids: 271, Cache hits: 14
12:51:32.825 [RxCachedThreadScheduler-4] DEBUG f.c.p.b.JsonRpcBlockToBitcoinBundleConverter - Transactions - Total ids: 2192, Cache hits: 4
12:51:47.587 [RxCachedThreadScheduler-5] DEBUG f.c.p.b.JsonRpcBlockToBitcoinBundleConverter - Transactions - Total ids: 489, Cache hits: 126
12:51:55.409 [RxCachedThreadScheduler-3] DEBUG f.c.p.b.JsonRpcBlockToBitcoinBundleConverter - Transactions - Total ids: 824, Cache hits: 75 
```
After that log, bitcoin pump stucks. Start points:

- bitcoind client crashed with OOM errors ( 10 gb is not enough). How much it needs?
- we create too large tx batch request ( total request is about 4k txes). General question -> find option query size for loading block tx.

**Comment by abitrolly** [comment]
This stuff is happening on Google Cloud.

**Comment by abitrolly** [comment]
Batch request - many `get_raw_transaction` in one request.

**Comment by litvintech** [comment]
@YodaMike Please provide your ideas about this tasks
1. how to be with bitcoind node (run pump with bitcoind node on ssd?)
2. about optimizing queries

**Comment by YodaMike** [comment]
1. I don't know, need some research, may be ssd will help
2. indeed we must tune our batch requests

**Comment by abitrolly** [comment]
Is there a link to metrics - x:blocknumber, y:blockpersecond?

**Comment by hleb-albau** [comment]
@abitrolly will be grafana dashboard with tons of metrics.

**Comment by abitrolly** [comment]
It is nice to see single PRs that address one issue. Fishing related commits one by one is not that useful for code review. Good job.
