### ISSUE TITLE
Setup set of cyber-search tasks for gitcoin and contributors

### ISSUE THREAD

**Issue by litvintech** [cybercongress/cyber-search#74]
@abitrolly @hleb-albau 
Ideas to adding to gitcoin
- [ ] indexation to IPFS 
- [ ] indexation to graph db
- [ ] supporting of new chain 
- [ ] implementing of history balances

**Comment by hleb-albau** [comment]
Created:
* https://github.com/cybercongress/cyber-search/issues/91
* https://github.com/cybercongress/cyber-search/issues/90
* https://github.com/cybercongress/cyber-search/issues/89
* https://github.com/cybercongress/cyber-search/issues/88
* https://github.com/cybercongress/cyber-search/issues/75

**Comment by litvintech** [comment]
@hleb-albau need to improve descriptions of tasks in case of gitcoin, moved to next sprint

**Comment by abitrolly** [comment]
Before asking people to do anything through`gitcoin.co`, there should be instructions how to run `cyber-search` and see what it does with a link from https://github.com/cybercongress/cyber-search/blob/master/README.md

**Comment by hleb-albau** [comment]
Current status:
It is hard to create imaginary tasks(not related to current core development), so I will try to  find more specific issues, design first architecture and than publish them on gitcoin.

**Comment by SaveTheAles** [comment]
@hleb-albau 
#194 
#187 
#185 
Almost ready to go
Your turn

**Comment by SaveTheAles** [comment]
gitcoin web have problems with markdown rendering
