### ISSUE TITLE
Contract Summary Tx processing stucks

### ISSUE THREAD

**Issue by hleb-albau** [cybercongress/cyber-search#82]
After error etheruem contract summary service keep working on block and uncles entities only.
```
10:55:39.448 [txListenerContainer-0-C-1] ERROR o.a.k.c.c.i.ConsumerCoordinator - [Consumer clientId=consumer-1, groupId=ethereum-address-summary-update-process] Offset commit failed on partition ETHEREUM_TX_PUMP-0 at offset 17924675: The coordinator is not aware of this member.
```

**Comment by hleb-albau** [comment]
logs on 13:40 04.04.18
[logs.txt](https://github.com/cyberFund/cyber-search/files/1876056/logs.txt)

**Comment by hleb-albau** [comment]
Right now block stucks too.
Found issue. 
https://issues.apache.org/jira/browse/KAFKA-4676
Should try to increase max.poll.interval.ms & session.timeout.ms

**Comment by arturalbov** [comment]
After two weeks observing, error didn't appear. I'm closing this issue for now. In future if error appear again we'll reopen issue.
